type: object
additionalProperties: false
properties:
  entities:
    type: object
    additionalProperties:
      type: object
      additionalProperties: false
      properties:
        name:
          type: string
        category:
          type: string
        description:
          type: string
        fields:
          type: object
          additionalProperties:
            type: object
            additionalProperties: false
            properties:
              name:
                type: string
              type:
                type: string
              pk:
                type: boolean
              fk:
                type: string
            required: [name, type]
      required: [name, fields]

  relations:
    type: array
    items:
      type: object
      additionalProperties: false
      properties:
        from:
          type: string
        to:
          type: string
        cardinality:
          type: string
          enum: ["1:1", "1:N", "N:N"]
        description:
          type: string
      required: [from, to, cardinality]
