type: object
additionalProperties: false
properties:
  members:
    type: object
    additionalProperties:
      type: object
      additionalProperties: false
      properties:
        name:
          type: string
        role:
          type: string
        description:
          type: string
      required: [name, role]
