type: object
properties:
  entities:
    type: object
    additionalProperties:
      type: object
      properties:
        attributes:
          type: object
          additionalProperties:
            type: object
            properties:
              type:
                type: string
              required:
                type: boolean
            additionalProperties: false
            required: [type, required]
      additionalProperties: false
      required: [attributes]

  references:
    type: array
    items:
      type: object
      properties:
        from:
          type: string
        to:
          type: string
      additionalProperties: false
      required: [from, to]

  categories:
    type: object
    additionalProperties:
      type: object
      properties:
        title:
          type: string
        impl_paths:
          type: array
          items:
            type: string
        spec:
          type: string
        tasks:
          type: object
          additionalProperties:
            type: object
            properties:
              title:
                type: string
              note:
                type: string
              phase:
                type: integer
              done:
                type: boolean
            additionalProperties: false
            required: [title, phase]
      additionalProperties: false
      required: [title, impl_paths, tasks]
additionalProperties: false
